add content to css and html
catharkriss/hw.styling-forms pull request #1
Opened 2024-07-01 21:16 UTC by catharkriss

підкажи, будь ласка, які стилі застосувати до віконця завантаження і видалення, щоб вони були в рядочок?

2024-07-04 14:35 UTC, a1exalexander commented
> підкажи, будь ласка, які стилі застосувати до віконця завантаження і видалення, щоб вони були в рядочок?

 flex

2024-07-04 14:46 UTC, a1exalexander requested changes
![image](https://github.com/catharkriss/hw.styling-forms/assets/40409129/9750fd61-25d0-4f3b-9471-30d478bcdbc7)

1. відступ від заголовка до лейбла
2. радіус інпута не той, що треба
3. відступ від інпута до текста
4. радіо не працюють + не по дизайну
5. колір вже обраного елемента має бути темним вже
6. відступ між лінком та текстом
7. відступи від заголовка до лого
8. в один рядок

2024-07-04 14:46 UTC, a1exalexander commented on index.html
> +            <h1 class="profile-title">Profile</h1>
на 1 сторінці сайта  1 тег `h1`

2024-07-04 14:46 UTC, a1exalexander commented on index.html
> +            <h1 class="profile-title">Profile</h1>
[Avoid using multiple `<h1>` elements on one page](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Heading_Elements#avoid_using_multiple_h1_elements_on_one_page)

2024-07-07 14:00 UTC, catharkriss commented on index.html
> +            <h1 class="profile-title">Profile</h1>
додала всі зазначені зміни. але
я не розумію як зробити лише select сіреньким, не чипаючи при цьому інші option...
і не знаю як розмістити up to 1mb саме під віконцем завантаження. justify-self не працює, якщо додати цей span в один дів з ними: лише align-self працює....

2024-07-11 12:23 UTC, a1exalexander approved these changes
Приймаю!
Але виправ ще два моменти
![image](https://github.com/catharkriss/hw.styling-forms/assets/40409129/8872d7ff-90b0-48af-b08c-04733576b585)

1. не вирівняна по лівій стороні кортинка
2. відступ від інпута до текста по краям має бути

2024-07-11 16:27 UTC, merged